-- Local development seed data — NOT a Flyway migration.
--
-- Lives outside db/migration/ on purpose so Flyway never picks it up. Loaded by hand,
-- never automatically. Content is AI-generated and human-reviewed through the app's own
-- ingestion pipeline; baking it into migrations would contradict that architecture.
--
-- TODO: stopgap. Cross-cutting demo/sample data should move to a dedicated demo-data
-- repository shared across developers, testers, and QA.
--
-- Conventions:
--   * Safe to run repeatedly.
--   * id and created_at are generated by the database — never supply them here.
--   * Keep parents before children so foreign keys resolve.
--
-- Load (idempotent):
--   docker exec -i practiq-api-postgres-1 psql -U practiq -d practiq < src/main/resources/db/seed_local.sql
--
-- Hard reset (clean slate — drops rows no longer in this file):
--   docker exec -i practiq-api-postgres-1 psql -U practiq -d practiq -c 'TRUNCATE concept, question CASCADE;'

-- ---------------------------------------------------------------------------
-- Concepts
-- Board-agnostic, granular units of knowledge. Natural key: name.
-- ---------------------------------------------------------------------------
insert into concept (name, description)
values ('Scalars and Vectors',
        'Distinguishing quantities with magnitude only from those with both magnitude and direction.'),
       ('Speed and Velocity', 'Rate of change of distance versus rate of change of displacement, and how they differ.'),
       ('Acceleration', 'How the velocity of an object changes over time, including deceleration.'),
       ('Newton''s First Law', 'An object stays at rest or in uniform motion unless acted on by a resultant force.'),
       ('Newton''s Second Law', 'The resultant force on an object equals its mass multiplied by its acceleration.'),
       ('Hooke''s Law',
        'The extension of an elastic object is proportional to the force applied, up to the limit of proportionality.'),
       ('Energy Stores and Transfers',
        'How energy is held in stores and shifted between them during physical processes.'),
       ('Conservation of Energy', 'Energy cannot be created or destroyed, only transferred, stored, or dissipated.'),
       ('Electrical Charge and Current', 'Current as the rate of flow of charge around a closed circuit.'),
       ('Potential Difference', 'The energy transferred per unit charge between two points in a circuit.'),
       ('Wave Properties', 'Describing waves using amplitude, wavelength, frequency, and period.'),
       ('Diffraction', 'The spreading out of waves as they pass through a gap or around an obstacle.')
on conflict (name) do nothing;

-- ── Questions + mark schemes ───────────────────────────────────────────────
-- Body, concept links, and mark scheme are authored together, once, in the staging
-- table below — never as separate lists matched by a text key (that drift silently
-- linked nothing in an earlier version of this script). See D-016.
--
-- source is deliberately not all 'SEED', and mark_scheme is deliberately null on some
-- rows: a null means no mark_scheme row is created at all (D-018 — it's a separate
-- table, so "no mark scheme" is an absent row, not a null column). Mostly correlates
-- with PENDING/REJECTED, but one APPROVED row has none on purpose — absence isn't
-- mechanically tied to status, and it keeps the "visible question, no scheme" path
-- reachable locally.
--
-- All mark scheme content is self-written. No past-paper prose — see the copyright rule.
create temporary table seed_questions as
select *
from (values ('Which of the following is a vector quantity?

- [ ] Speed
- [ ] Mass
- [x] Velocity
- [ ] Time',
              1, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Scalars and Vectors'],
              '**1 mark**

- **Velocity** (1)

*Velocity has both magnitude and direction. Speed, mass and time are scalars.*'),

             ('A car travels 150 m in 10 s. Calculate its average speed.',
              null, 'SHORT_ANSWER', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Speed and Velocity'],
              '**2 marks**

- Correct substitution into `speed = distance / time` → `150 / 10` (1)
- `15 m/s` — unit required (1)

*Award both marks for a correct answer with no working.*'),

             ('A 900 kg car accelerates uniformly from rest to 24 m/s in 8 s. (a) Calculate the car''s acceleration. (b) Calculate the resultant force needed to produce this acceleration. (c) State one reason the force needed in practice would be greater than your answer to (b).',
              null, 'EXTENDED', 'EXTRACTED', 'PENDING', 'AQA GCSE Physics',
              array ['Acceleration', 'Newton''s Second Law'], null),

             ('State Newton''s First Law.',
              2, 'SHORT_ANSWER', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Newton''s First Law'],
              '**2 marks**

- An object remains at rest, or continues at constant velocity (1)
- unless acted on by a resultant force (1)

*Accept "zero resultant force" for the second mark. Do not accept "no force".*'),

             ('Two students investigate the relationship between force and acceleration for a trolley of constant mass. They apply increasing force to the trolley and measure its acceleration each time. (a) Sketch the shape of the graph you would expect if acceleration is plotted against force. (b) State the relationship between force and acceleration shown by this graph. (c) The trolley has a mass of 1.5 kg. Calculate the force needed to accelerate it at 4 m/s squared.',
              null, null, 'GENERATED', 'PENDING', null, array ['Newton''s Second Law', 'Acceleration'], null),

             ('A resultant force of 10 N acts on an object of mass 2 kg. What is the object''s acceleration?

- [ ] 0.2 m/s squared
- [ ] 2.5 m/s squared
- [x] 5 m/s squared
- [ ] 20 m/s squared',
              2, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Newton''s Second Law'],
              '**1 mark**

- **5 m/s squared** (1)

*From `a = F / m` → `10 / 2`.*'),

             ('A spring has a natural length of 12 cm. When a 2 N force is applied, it stretches to 15 cm. Calculate the spring constant, stating the correct unit.',
              null, 'SHORT_ANSWER', 'EXTRACTED', 'PENDING', 'AQA GCSE Physics', array ['Hooke''s Law'], null),

             ('A student stretches a spring within its limit of proportionality by applying a force and measuring the extension. (a) State Hooke''s Law. (b) The spring has a spring constant of 40 N/m and is extended by 0.05 m. Calculate the elastic potential energy stored in the spring. (c) State what happens to this stored energy if the spring is released and allowed to return to its natural length with nothing attached.',
              3, 'EXTENDED', 'SEED', 'APPROVED', 'AQA GCSE Physics',
              array ['Hooke''s Law', 'Energy Stores and Transfers'],
              '**5 marks**

**(a)** Extension is directly proportional to the force applied (1), up to the limit of proportionality (1)

**(b)** `E = 0.5 × k × e²` → `0.5 × 40 × 0.05²` (1) = `0.05 J` (1)

**(c)** Transferred to the kinetic energy store of the spring as it recoils, then dissipated to the thermal store of the surroundings (1)

*(b): allow error carried forward from an incorrect substitution. Unit required for the final mark.*'),

             ('A ball is thrown upwards and reaches its highest point. Which energy store increased as the ball rose?

- [ ] Kinetic
- [x] Gravitational potential
- [ ] Chemical
- [ ] Thermal',
              1, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Energy Stores and Transfers'], null),

             ('A skier of mass 60 kg starts from rest at the top of a slope 20 m high and reaches the bottom with a speed of 18 m/s. (a) Calculate the gravitational potential energy the skier had at the top of the slope, taking g = 10 N/kg. (b) Calculate the kinetic energy the skier has at the bottom. (c) Use the principle of conservation of energy to explain why your answers to (a) and (b) are not equal, and state where the missing energy has gone.',
              4, 'EXTENDED', 'GENERATED', 'APPROVED', null,
              array ['Conservation of Energy', 'Energy Stores and Transfers'],
              '**6 marks**

**(a)** `E = m × g × h` → `60 × 10 × 20` (1) = `12 000 J` (1)

**(b)** `E = 0.5 × m × v²` → `0.5 × 60 × 18²` (1) = `9 720 J` (1)

**(c)** Energy is conserved, so the difference of `2 280 J` has not been destroyed (1). It has been dissipated to the thermal store of the surroundings by friction and air resistance (1)

*(c): accept "transferred to thermal/internal energy by friction". Do not accept "lost" or "used up" alone.*'),

             ('A charge of 15 C flows past a point in a wire in 5 s. Calculate the current in the wire.',
              2, 'SHORT_ANSWER', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Electrical Charge and Current'],
              '**2 marks**

- Correct substitution into `I = Q / t` → `15 / 5` (1)
- `3 A` — unit required (1)'),

             ('What is the unit of electric current?

- [ ] Ampere
- [x] Ampere
- [ ] Volt
- [ ] Watt',
              1, 'MCQ', 'EXTRACTED', 'REJECTED', 'AQA GCSE Physics', array ['Electrical Charge and Current'], null),

             ('A battery transfers 24 J of energy to 4 C of charge as it flows through a circuit. (a) Define potential difference. (b) Calculate the potential difference of the battery. (c) Explain, in terms of energy, what a voltmeter placed across a component in the circuit is measuring.',
              3, 'EXTENDED', 'SEED', 'APPROVED', 'AQA GCSE Physics',
              array ['Potential Difference', 'Electrical Charge and Current'],
              '**4 marks**

**(a)** The energy transferred per unit charge between two points (1)

**(b)** `V = E / Q` → `24 / 4` = `6 V` (1)

**(c)** The energy transferred per coulomb of charge (1) as it passes through that component (1)

*(a): accept "energy per coulomb". Do not accept "the push" or "the force".*'),

             ('The diagram below shows a transverse wave.

{{s3:diagrams/transverse-wave.svg}}

(a) Use the diagram to state the amplitude of the wave in the units shown. (b) State the wavelength of the wave in the units shown.',
              2, 'SHORT_ANSWER', 'EXTRACTED', 'APPROVED', 'AQA GCSE Physics', array ['Wave Properties'],
              '**2 marks**

**(a)** `3 cm` (1) — allow 2.8 to 3.2

**(b)** `8 cm` (1) — allow 7.8 to 8.2

*(a): do not credit peak-to-trough distance (6 cm) — amplitude is measured from the rest position.*'),

             ('A wave has a frequency of 50 Hz and a wavelength of 4 m. What is its wave speed?

- [ ] 12.5 m/s
- [x] 200 m/s
- [ ] 0.08 m/s
- [ ] 54 m/s',
              2, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Wave Properties'],
              '**1 mark**

- **200 m/s** (1)

*From `v = f × λ` → `50 × 4`.*'),

             ('The diagram below shows plane waves approaching a barrier with a narrow gap.

{{s3:diagrams/diffraction-gap.svg}}

(a) Describe what happens to the waves as they pass through the gap. (b) State how the amount of diffraction would change if the gap were made narrower, relative to the wavelength of the waves.',
              null, 'EXTENDED', 'EXTRACTED', 'PENDING', 'AQA GCSE Physics',
              array ['Diffraction', 'Wave Properties'],
              null)) as t(body, difficulty, type, source, status, source_spec, concept_names, mark_scheme);

-- mark_scheme rows cascade from question, so this delete clears them too.
delete
from question
where body in (select body from seed_questions);

with inserted as (
    insert into question (body, difficulty, type, source, status, source_spec)
        select body, difficulty, type, source, status, source_spec from seed_questions
        returning id, body),
     links as (
         insert into question_concept (question_id, concept_id)
             select i.id, c.id
             from inserted i
                      join seed_questions sq on sq.body = i.body
                      join concept c on c.name = any (sq.concept_names)
             on conflict do nothing)
insert
into mark_scheme (question_id, body)
select i.id, sq.mark_scheme
from inserted i
         join seed_questions sq on sq.body = i.body
where sq.mark_scheme is not null;

drop table seed_questions;