-- Local development seed data — NOT a Flyway migration.
--
-- This file lives outside db/migration/ on purpose, so Flyway never picks it up.
-- It exists only to give a developer some rows to eyeball while poking at the app
-- locally (e.g. GET /api/v1/concepts). It is loaded by hand, never automatically.
--
-- Why it isn't a migration: concepts and other content will ultimately be
-- AI-generated and human-reviewed through the application's own ingestion pipeline.
-- Baking content into migrations would contradict that architecture, so seed data
-- and schema are kept strictly separate.
--
-- TODO: this is a stopgap. Cross-cutting demo/sample data should eventually move to
-- a dedicated demo-data repository shared across developers, testers, and QA, rather
-- than living in the API repo.
--
-- Conventions for this file:
--   * Safe to run repeatedly. Every insert is idempotent (ON CONFLICT DO NOTHING
--     against a natural unique key), so re-running adds nothing and errors nothing.
--   * id and created_at are generated by the database — never supply them here.
--   * Add new data types as their own clearly-headed section below, following the
--     same idempotent pattern. Keep parents before children so foreign keys resolve.
--
-- Load (idempotent — run it as often as you like):
--   docker exec -i practiq-api-postgres-1 psql -U practiq -d practiq < src/main/resources/db/seed_local.sql
--
-- Hard reset (only if you want a clean slate, e.g. to drop rows no longer in this file):
--   docker exec -i practiq-api-postgres-1 psql -U practiq -d practiq -c 'TRUNCATE concept CASCADE;'

-- ---------------------------------------------------------------------------
-- Concepts
-- Board-agnostic, granular units of knowledge. Natural key: name.
-- ---------------------------------------------------------------------------
insert into concept (name, description)
values ('Scalars and Vectors',
        'Distinguishing quantities with magnitude only from those with both magnitude and direction.'),
       ('Speed and Velocity', 'Rate of change of distance versus rate of change of displacement, and how they differ.'),
       ('Acceleration', 'How the velocity of an object changes over time, including deceleration.'),
       ('Newton''s First Law', 'An object stays at rest or in uniform motion unless acted on by a resultant force.'),
       ('Newton''s Second Law', 'The resultant force on an object equals its mass multiplied by its acceleration.'),
       ('Hooke''s Law',
        'The extension of an elastic object is proportional to the force applied, up to the limit of proportionality.'),
       ('Energy Stores and Transfers',
        'How energy is held in stores and shifted between them during physical processes.'),
       ('Conservation of Energy', 'Energy cannot be created or destroyed, only transferred, stored, or dissipated.'),
       ('Electrical Charge and Current', 'Current as the rate of flow of charge around a closed circuit.'),
       ('Potential Difference', 'The energy transferred per unit charge between two points in a circuit.'),
       ('Wave Properties', 'Describing waves using amplitude, wavelength, frequency, and period.'),
       ('Diffraction', 'The spreading out of waves as they pass through a gap or around an obstacle.')
on conflict (name) do nothing;

-- ── Questions ──────────────────────────────────────────────────────────────
-- No natural unique key exists on question (unlike concept.name), so this
-- section is idempotent by a different mechanism: delete all source='seed'
-- rows, then re-insert. Safe to re-run; never touches AI-generated content,
-- which uses source='generated'. question_concept has ON DELETE CASCADE
-- (see migration), so deleting the question rows cleans up their links
-- automatically — no separate delete step needed for question_concept.
delete
from question
where source = 'seed';

insert into question (body, mark_scheme, difficulty, type, source, status, source_spec)
values ('Which of the following is a vector quantity?

- [ ] Speed
- [ ] Mass
- [x] Velocity
- [ ] Time',
        'Velocity is a vector because it has both magnitude and direction; the others are scalars.',
        1, 'mcq', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A cyclist travels 300 m north in 60 s, then 300 m south in 60 s, returning to her start point. Calculate her average speed and her average velocity for the whole journey, and explain why they are different.',
        'Average speed = total distance / total time = 600 / 120 = 5 m/s. Average velocity = total displacement / total time = 0 / 120 = 0 m/s. They differ because speed depends on distance travelled while velocity depends on displacement, which is zero here since she returns to her starting point.',
        2, 'short_answer', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A 900 kg car accelerates uniformly from rest to 24 m/s in 8 s. (a) Calculate the car''s acceleration. (b) Calculate the resultant force needed to produce this acceleration. (c) State one reason the force needed in practice would be greater than your answer to (b).',
        '(a) a = delta-v / t = 24/8 = 3 m/s squared. (b) F = ma = 900 x 3 = 2700 N. (c) Any valid reason, e.g. friction/air resistance/drag must also be overcome, so the engine must provide extra force beyond that needed for acceleration alone.',
        3, 'extended', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A book rests on a table and remains stationary. State Newton''s First Law and use it to explain why the book does not accelerate.',
        'Newton''s First Law: an object stays at rest, or moves at a constant velocity, unless acted on by a resultant (unbalanced) force. The book does not accelerate because the weight of the book acting downward is balanced by the normal contact force from the table acting upward, so the resultant force is zero.',
        2, 'short_answer', 'seed', 'approved', 'AQA GCSE Physics'),

       ('Two students investigate the relationship between force and acceleration for a trolley of constant mass. They apply increasing force to the trolley and measure its acceleration each time. (a) Sketch the shape of the graph you would expect if acceleration is plotted against force. (b) State the relationship between force and acceleration shown by this graph. (c) The trolley has a mass of 1.5 kg. Calculate the force needed to accelerate it at 4 m/s squared.',
        '(a) A straight line through the origin. (b) Acceleration is directly proportional to the resultant force, for a constant mass. (c) F = ma = 1.5 x 4 = 6 N.',
        4, 'extended', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A resultant force of 10 N acts on an object of mass 2 kg. What is the object''s acceleration?

- [ ] 0.2 m/s squared
- [ ] 2.5 m/s squared
- [x] 5 m/s squared
- [ ] 20 m/s squared',
        'a = F/m = 10/2 = 5 m/s squared.',
        2, 'mcq', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A spring has a natural length of 12 cm. When a 2 N force is applied, it stretches to 15 cm. Calculate the spring constant, stating the correct unit.',
        'Extension = 15 - 12 = 3 cm = 0.03 m. k = F/e = 2/0.03 = 66.7 N/m (3 s.f.).',
        2, 'short_answer', 'seed', 'pending', 'AQA GCSE Physics'),

       ('A student stretches a spring within its limit of proportionality by applying a force and measuring the extension. (a) State Hooke''s Law. (b) The spring has a spring constant of 40 N/m and is extended by 0.05 m. Calculate the elastic potential energy stored in the spring. (c) State what happens to this stored energy if the spring is released and allowed to return to its natural length with nothing attached.',
        '(a) The extension of an elastic object is directly proportional to the force applied, provided the limit of proportionality is not exceeded. (b) E = half x k x e squared = 0.5 x 40 x 0.05 squared = 0.05 J. (c) The elastic potential energy is transferred to the kinetic energy store of the spring as it moves, and eventually to the surroundings (e.g. as heat/sound) as the spring''s motion is damped.',
        3, 'extended', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A ball is thrown upwards and reaches its highest point. Which energy store increased as the ball rose?

- [ ] Kinetic
- [x] Gravitational potential
- [ ] Chemical
- [ ] Thermal',
        'As the ball rises its height increases, so the gravitational potential energy store increases while the kinetic energy store decreases.',
        1, 'mcq', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A skier of mass 60 kg starts from rest at the top of a slope 20 m high and reaches the bottom with a speed of 18 m/s. (a) Calculate the gravitational potential energy the skier had at the top of the slope, taking g = 10 N/kg. (b) Calculate the kinetic energy the skier has at the bottom. (c) Use the principle of conservation of energy to explain why your answers to (a) and (b) are not equal, and state where the missing energy has gone.',
        '(a) GPE = mgh = 60 x 10 x 20 = 12000 J. (b) KE = half x m x v squared = 0.5 x 60 x 18 squared = 9720 J. (c) Energy is conserved overall - it cannot be created or destroyed. The difference (12000 - 9720 = 2280 J) has been transferred to the thermal energy store of the skis, snow and surrounding air due to friction and air resistance, rather than remaining in the kinetic store.',
        4, 'extended', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A charge of 15 C flows past a point in a wire in 5 s. Calculate the current in the wire.',
        'I = Q/t = 15/5 = 3 A.',
        2, 'short_answer', 'seed', 'approved', 'AQA GCSE Physics'),

       ('What is the unit of electric current?

- [ ] Ampere
- [x] Ampere
- [ ] Volt
- [ ] Watt',
        'Current is measured in amperes (A).',
        1, 'mcq', 'seed', 'rejected', 'AQA GCSE Physics'),

       ('A battery transfers 24 J of energy to 4 C of charge as it flows through a circuit. (a) Define potential difference. (b) Calculate the potential difference of the battery. (c) Explain, in terms of energy, what a voltmeter placed across a component in the circuit is measuring.',
        '(a) Potential difference is the energy transferred per unit charge passing between two points in a circuit. (b) V = E/Q = 24/4 = 6 V. (c) The voltmeter measures the energy transferred per unit charge to that component specifically - i.e. how much electrical energy is converted to other forms (e.g. thermal, light) as each coulomb of charge passes through it.',
        3, 'extended', 'seed', 'approved', 'AQA GCSE Physics'),

       ('The diagram below shows a transverse wave.

{{s3:diagrams/transverse-wave.svg}}

(a) Use the diagram to state the amplitude of the wave in the units shown. (b) State the wavelength of the wave in the units shown.',
        '(a) The amplitude is the distance from the midline to the peak (or trough) of the wave, as labelled. (b) The wavelength is the distance between two adjacent, equivalent points on the wave (e.g. peak to peak), as labelled.',
        2, 'short_answer', 'seed', 'approved', 'AQA GCSE Physics'),

       ('A wave has a frequency of 50 Hz and a wavelength of 4 m. What is its wave speed?

- [ ] 12.5 m/s
- [x] 200 m/s
- [ ] 0.08 m/s
- [ ] 54 m/s',
        'v = f x lambda = 50 x 4 = 200 m/s.',
        2, 'mcq', 'seed', 'approved', 'AQA GCSE Physics'),

       ('The diagram below shows plane waves approaching a barrier with a narrow gap.

{{s3:diagrams/diffraction-gap.svg}}

(a) Describe what happens to the waves as they pass through the gap. (b) State how the amount of diffraction would change if the gap were made narrower, relative to the wavelength of the waves.',
        '(a) The waves spread out (diffract) after passing through the gap, becoming curved/circular wavefronts rather than continuing as straight parallel wavefronts. (b) The amount of diffraction increases as the gap is made narrower relative to the wavelength - diffraction is most pronounced when the gap width is similar to the wavelength.',
        4, 'extended', 'seed', 'approved', 'AQA GCSE Physics');

-- ── Question ↔ Concept links ──────────────────────────────────────────────
-- Matched by the first 40 characters of body (unique per question here) rather
-- than repeating full question text. Several questions are deliberately
-- synoptic (linked to more than one concept). ON CONFLICT is defensive only —
-- a fresh insert following the delete above means no conflicts are possible,
-- but it costs nothing to leave in.
insert into question_concept (question_id, concept_id)
select q.id, c.id
from (values ('Which of the following is a vector qua', 'Scalars and Vectors'),
             ('A cyclist travels 300 m north in 60 s,', 'Speed and Velocity'),
             ('A 900 kg car accelerates uniformly fro', 'Acceleration'),
             ('A 900 kg car accelerates uniformly fro', 'Newton''s Second Law'),
             ('A book rests on a table and remains st', 'Newton''s First Law'),
             ('Two students investigate the relations', 'Newton''s Second Law'),
             ('Two students investigate the relations', 'Acceleration'),
             ('A resultant force of 10 N acts on an o', 'Newton''s Second Law'),
             ('A spring has a natural length of 12 cm', 'Hooke''s Law'),
             ('A student stretches a spring within it', 'Hooke''s Law'),
             ('A student stretches a spring within it', 'Energy Stores and Transfers'),
             ('A ball is thrown upwards and reaches i', 'Energy Stores and Transfers'),
             ('A skier of mass 60 kg starts from rest', 'Conservation of Energy'),
             ('A skier of mass 60 kg starts from rest', 'Energy Stores and Transfers'),
             ('A charge of 15 C flows past a point in', 'Electrical Charge and Current'),
             ('What is the unit of electric current?', 'Electrical Charge and Current'),
             ('A battery transfers 24 J of energy to ', 'Potential Difference'),
             ('A battery transfers 24 J of energy to ', 'Electrical Charge and Current'),
             ('The diagram below shows a transverse w', 'Wave Properties'),
             ('A wave has a frequency of 50 Hz and a ', 'Wave Properties'),
             ('The diagram below shows plane waves ap', 'Diffraction'),
             ('The diagram below shows plane waves ap', 'Wave Properties')) as links(body_key, concept_name)
         join question q on left(q.body, 40) = links.body_key and q.source = 'seed'
         join concept c on c.name = links.concept_name
on conflict do nothing;