-- Local development seed data — NOT a Flyway migration.
--
-- This file lives outside db/migration/ on purpose, so Flyway never picks it up.
-- It exists only to give a developer some DBRows to eyeball while poking at the app
-- locally (e.g. GET /api/v1/concepts). It is loaded by hand, never automatically.
--
-- Why it isn't a migration: concepts and other content will ultimately be
-- AI-generated and human-reviewed through the application's own ingestion pipeline.
-- Baking content into migrations would contradict that architecture, so seed data
-- and schema are kept strictly separate.
--
-- TODO: this is a stopgap. Cross-cutting demo/sample data should eventually move to
-- a dedicated demo-data repository shared across developers, testers, and QA, rather
-- than living in the API repo.
--
-- Conventions for this file:
--   * Safe to run repeatedly. Every insert is idempotent (ON CONFLICT DO NOTHING
--     against a natural unique key), so re-running adds nothing and errors nothing.
--   * id and created_at are generated by the database — never supply them here.
--   * Add new data types as their own clearly-headed section below, following the
--     same idempotent pattern. Keep parents before children so foreign keys resolve.
--
-- Load (idempotent — run it as often as you like):
--   docker exec -i practiq-api-postgres-1 psql -U practiq -d practiq < src/main/resources/db/seed_local.sql
--
-- Hard reset (only if you want a clean slate, e.g. to drop DBRows no longer in this file):
--   docker exec -i practiq-api-postgres-1 psql -U practiq -d practiq -c 'TRUNCATE concept CASCADE;'

-- ---------------------------------------------------------------------------
-- Concepts
-- Board-agnostic, granular units of knowledge. Natural key: name.
-- ---------------------------------------------------------------------------
insert into concept (name, description)
values ('Scalars and Vectors',
        'Distinguishing quantities with magnitude only from those with both magnitude and direction.'),
       ('Speed and Velocity', 'Rate of change of distance versus rate of change of displacement, and how they differ.'),
       ('Acceleration', 'How the velocity of an object changes over time, including deceleration.'),
       ('Newton''s First Law', 'An object stays at rest or in uniform motion unless acted on by a resultant force.'),
       ('Newton''s Second Law', 'The resultant force on an object equals its mass multiplied by its acceleration.'),
       ('Hooke''s Law',
        'The extension of an elastic object is proportional to the force applied, up to the limit of proportionality.'),
       ('Energy Stores and Transfers',
        'How energy is held in stores and shifted between them during physical processes.'),
       ('Conservation of Energy', 'Energy cannot be created or destroyed, only transferred, stored, or dissipated.'),
       ('Electrical Charge and Current', 'Current as the rate of flow of charge around a closed circuit.'),
       ('Potential Difference', 'The energy transferred per unit charge between two points in a circuit.'),
       ('Wave Properties', 'Describing waves using amplitude, wavelength, frequency, and period.'),
       ('Diffraction', 'The spreading out of waves as they pass through a gap or around an obstacle.')
on conflict (name) do nothing;

-- ── Questions ──────────────────────────────────────────────────────────────
-- Body text and its concept links are authored together, once, in the staging
-- table below — not as two separately hand-maintained lists matched by a
-- fragile text-prefix key (that drift was the actual cause of a previous
-- version of this script silently linking nothing).
--
-- source is deliberately NOT all 'SEED' — see D-016 for why a mixed
-- SEED/EXTRACTED/GENERATED spread with nulls is more representative for
-- local dev than uniformly-complete hand-authored content.
--
-- No mark_scheme column — see D-018. Not reintroduced here until the
-- replacement design is settled.
create temporary table seed_questions as
select *
from (values ('Which of the following is a vector quantity?

- [ ] Speed
- [ ] Mass
- [x] Velocity
- [ ] Time',
              1, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Scalars and Vectors']),

             ('A car travels 150 m in 10 s. Calculate its average speed.',
              null, 'SHORT_ANSWER', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Speed and Velocity']),

             ('A 900 kg car accelerates uniformly from rest to 24 m/s in 8 s. (a) Calculate the car''s acceleration. (b) Calculate the resultant force needed to produce this acceleration. (c) State one reason the force needed in practice would be greater than your answer to (b).',
              null, 'EXTENDED', 'EXTRACTED', 'PENDING', 'AQA GCSE Physics',
              array ['Acceleration', 'Newton''s Second Law']),

             ('State Newton''s First Law.',
              2, 'SHORT_ANSWER', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Newton''s First Law']),

             ('Two students investigate the relationship between force and acceleration for a trolley of constant mass. They apply increasing force to the trolley and measure its acceleration each time. (a) Sketch the shape of the graph you would expect if acceleration is plotted against force. (b) State the relationship between force and acceleration shown by this graph. (c) The trolley has a mass of 1.5 kg. Calculate the force needed to accelerate it at 4 m/s squared.',
              null, null, 'GENERATED', 'PENDING', null, array ['Newton''s Second Law', 'Acceleration']),

             ('A resultant force of 10 N acts on an object of mass 2 kg. What is the object''s acceleration?

- [ ] 0.2 m/s squared
- [ ] 2.5 m/s squared
- [x] 5 m/s squared
- [ ] 20 m/s squared',
              2, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Newton''s Second Law']),

             ('A spring has a natural length of 12 cm. When a 2 N force is applied, it stretches to 15 cm. Calculate the spring constant, stating the correct unit.',
              null, 'SHORT_ANSWER', 'EXTRACTED', 'PENDING', 'AQA GCSE Physics', array ['Hooke''s Law']),

             ('A student stretches a spring within its limit of proportionality by applying a force and measuring the extension. (a) State Hooke''s Law. (b) The spring has a spring constant of 40 N/m and is extended by 0.05 m. Calculate the elastic potential energy stored in the spring. (c) State what happens to this stored energy if the spring is released and allowed to return to its natural length with nothing attached.',
              3, 'EXTENDED', 'SEED', 'APPROVED', 'AQA GCSE Physics',
              array ['Hooke''s Law', 'Energy Stores and Transfers']),

             ('A ball is thrown upwards and reaches its highest point. Which energy store increased as the ball rose?

- [ ] Kinetic
- [x] Gravitational potential
- [ ] Chemical
- [ ] Thermal',
              1, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Energy Stores and Transfers']),

             ('A skier of mass 60 kg starts from rest at the top of a slope 20 m high and reaches the bottom with a speed of 18 m/s. (a) Calculate the gravitational potential energy the skier had at the top of the slope, taking g = 10 N/kg. (b) Calculate the kinetic energy the skier has at the bottom. (c) Use the principle of conservation of energy to explain why your answers to (a) and (b) are not equal, and state where the missing energy has gone.',
              4, 'EXTENDED', 'GENERATED', 'APPROVED', null,
              array ['Conservation of Energy', 'Energy Stores and Transfers']),

             ('A charge of 15 C flows past a point in a wire in 5 s. Calculate the current in the wire.',
              2, 'SHORT_ANSWER', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Electrical Charge and Current']),

             ('What is the unit of electric current?

- [ ] Ampere
- [x] Ampere
- [ ] Volt
- [ ] Watt',
              1, 'MCQ', 'EXTRACTED', 'REJECTED', 'AQA GCSE Physics', array ['Electrical Charge and Current']),

             ('A battery transfers 24 J of energy to 4 C of charge as it flows through a circuit. (a) Define potential difference. (b) Calculate the potential difference of the battery. (c) Explain, in terms of energy, what a voltmeter placed across a component in the circuit is measuring.',
              3, 'EXTENDED', 'SEED', 'APPROVED', 'AQA GCSE Physics',
              array ['Potential Difference', 'Electrical Charge and Current']),

             ('The diagram below shows a transverse wave.

{{s3:diagrams/transverse-wave.svg}}

(a) Use the diagram to state the amplitude of the wave in the units shown. (b) State the wavelength of the wave in the units shown.',
              2, 'SHORT_ANSWER', 'EXTRACTED', 'APPROVED', 'AQA GCSE Physics', array ['Wave Properties']),

             ('A wave has a frequency of 50 Hz and a wavelength of 4 m. What is its wave speed?

- [ ] 12.5 m/s
- [x] 200 m/s
- [ ] 0.08 m/s
- [ ] 54 m/s',
              2, 'MCQ', 'SEED', 'APPROVED', 'AQA GCSE Physics', array ['Wave Properties']),

             ('The diagram below shows plane waves approaching a barrier with a narrow gap.

{{s3:diagrams/diffraction-gap.svg}}

(a) Describe what happens to the waves as they pass through the gap. (b) State how the amount of diffraction would change if the gap were made narrower, relative to the wavelength of the waves.',
              null, 'EXTENDED', 'EXTRACTED', 'PENDING', 'AQA GCSE Physics',
              array ['Diffraction', 'Wave Properties'])) as t(body, difficulty, type, source, status, source_spec, concept_names);

delete
from question
where body in (select body from seed_questions);

with inserted as (
    insert into question (body, difficulty, type, source, status, source_spec)
        select body, difficulty, type, source, status, source_spec from seed_questions
        returning id, body)
insert
into question_concept (question_id, concept_id)
select i.id, c.id
from inserted i
         join seed_questions sq on sq.body = i.body
         join concept c on c.name = any (sq.concept_names)
on conflict do nothing;

drop table seed_questions;