micronaut.application.name=practiq
datasources.default.db-type=postgresql
datasources.default.dialect=POSTGRES
//jpa.default.properties.hibernate.hbm2ddl.auto=none
flyway.datasources.default.enabled=true
