micronaut.application.name=practiq
datasources.default.url=jdbc:postgresql://localhost:5432/practiq
datasources.default.username=practiq
datasources.default.password=practiq_local
datasources.default.driver-class-name=org.postgresql.Driver
flyway.datasources.default.enabled=true
