micronaut.application.name=practiq
micronaut.serde.serialization.inclusion=always
micronaut.data.pageable.default-page-size=10
micronaut.data.pageable.max-page-size=50

datasources.default.db-type=postgresql
datasources.default.dialect=POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto=none
jpa.default.properties.hibernate.format_sql=true

flyway.datasources.default.enabled=true